Default: &defaults
  database: yefib.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: yefib_test.sqlite3
  <<: *defaults

Staging:
  database: yefib_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yefib_production.sqlite3
  poolsize: 100
  <<: *defaults